name: ecommerce_app
description: A new Flutter project.


publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^8.3.4
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.2
  titled_navigation_bar: ^4.1.0
  animated_size_and_fade: ^3.0.0
  progress_state_button: ^1.0.3
  nanoid: ^1.0.0
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  timelines: ^0.1.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#ea4b4b"
  image: assets/images/tshirt250.png
  android: true
  io: true




flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

    - family: PantonBold
      fonts:
        - asset: assets/fonts/panton/Panton-BlackCaps.otf

    - family: PantonBoldItalic
      fonts:
        - asset: assets/fonts/panton/Panton-BlackitalicCaps.otf

    - family: Panton
      fonts:
        - asset: assets/fonts/panton/Panton-LightCaps.otf

    - family: PantonItalic
      fonts:
        - asset: assets/fonts/panton/Panton-LightitalicCaps.otf
